site_name: Blabla Docs

theme:
  name: material

plugins:
  - mkdocstrings
  - tags:
      tags_file: tags.md

site_url: 'https://mgvalverde.github.io/experiment-gh-actions/'  # Trailing slash is recommended

#repo_name: mgvalverde/experiment-gh-actions  # hidden; too long
repo_url: https://github.com/mgvalverde/experiment-gh-actions

extra:
  version:
    provider: mike

nav:
  - Welcome: index.md
  - Tutorials: tutorials.md
  - How-to guides: how-to-guides.md
  - Explanation: explanation.md
  - Reference: reference.md
