name: Extract Tag Example  

on:  
  workflow_dispatch:
  workflow_call:
  

jobs:
  job1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.step1.outputs.target_tag }}
      output2: ${{ steps.step2.outputs.test }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - id: step1
        run: echo "target_tag=$(git describe --exact-match)" >> "$GITHUB_OUTPUT"
      - id: step2
        run: echo "test=world" >> "$GITHUB_OUTPUT"
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - env:
          OUTPUT1: ${{needs.job1.outputs.output1}}
          OUTPUT2: ${{needs.job1.outputs.output2}}
        run: echo "$OUTPUT1 $OUTPUT2"

