name: Publish to PyPI / GitHub

on:
  workflow_dispatch:
  workflow_call:

env:
  POETRY_VERSION: "1.8.3"
  PYTHON_VERSION: "3.9"

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build and publish to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://test.pypi.org/p/
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
      - uses: actions/checkout@v4
      - name: Install Poetry
        run: pipx install poetry==${{ env.POETRY_VERSION }}
      - name: Set up python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
