name: Publish Docs

on:
  workflow_dispatch:

  workflow_call:
    inputs:
      ref:
        description: "Tag. It'll be use to tag also the docs version. This tag must exists, and applied to an existing commit"
        type: string
        required: true
        default: ""

env:
  POETRY_VERSION: "1.8.3"
  PYTHON_VERSION: "3.9"

jobs:

  publish-docs:
    name: Publish Docs
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: write

    steps:
      - name: Get Tag
        run: | 
          if [[ "${{inputs.ref}}" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then  
              echo "TAG_VERSION=${{inputs.ref}}" >> $GITHUB_ENV  
            else  
              echo "TAG_VERSION=v$(poetry run semantic-release version --print-last-released )" >> $GITHUB_ENV
            fi

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install Poetry v${{ env.POETRY_VERSION }}
        run: pipx install poetry==${{ env.POETRY_VERSION }}
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: 'true'
          ref: ${{inputs.ref}}
      - name: Setup git user
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - name: Install dev dependencies
        run: poetry install --no-interaction --only=dev  # NOTE: this is needed for mkdocs etc
      - name: Publish new docs version
        run: poetry run mike deploy \
          --push \
          --update-aliases ${{inputs.ref}} latest
      - name: Set alias for latest
        run: poetry run mike set-default latest --push
