name: Build/Publish Latest Release Docs

on:
  release:
    types: [published]

permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install Poetry v${{ env.POETRY_VERSION }}
        run: pipx install poetry==${{ env.POETRY_VERSION }}
      - name: Install dev dependencies
        run: poetry install --no-interaction --only=dev  # NOTE: this is needed for mkdocs etc

      - name: Get target version
        run: echo "TARGET_VERSION=$(echo ${{github.event.release.tag_name}}  | sed -E 's/(v[0-9]+\.[0-9]+)\.[0-9]+/\1.x/')" >> $GITHUB_ENV

      - name: Setup Docs Deploy
        run: |
          git config --global user.name "Docs Deploy"
          git config --global user.email "users.noreply.github.com"

      - name: Build Docs Website
        run: | 
          poetry run mike deploy --push --update-aliases ${{ env.TARGET_VERSION }} latest          
#          poetry run mike set-default --push latest
