name: Publish Docs

on:
  workflow_dispatch:
  workflow_call:

env:
  POETRY_VERSION: "1.8.3"
  PYTHON_VERSION: "3.9"

jobs:

  publish-docs:
    name: Publish Docs
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: write

    steps:
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install Poetry v${{ env.POETRY_VERSION }}
        run: pipx install poetry==${{ env.POETRY_VERSION }}
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup git user
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - name: Install dev dependencies
        run: poetry install --no-interaction --only=dev  # NOTE: this is needed for mkdocs etc
      - name: Set env
        run: echo "PKG_VERSION=$(poetry run semantic-release version --print-last-released)" >> $GITHUB_ENV

      - name: Publish new docs version
        run: poetry run mike deploy \
          --push \
          --update-aliases $PKG_VERSION latest  # Calls another workflow
      - name: Set alias for latest
        run: poetry run mike set-default --push latest
