name:  Trigger Docs Build & Release
run-name: Trigger Docs Build & Release

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger GitHub pages rebuild
        run: |
          curl --fail --request POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $USER_TOKEN" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/pages/builds
        env:
          USER_TOKEN: ${{ secrets.PAT_PUBLISH_DOCS }}



